---
title: 'Week 7 - Normal distribution 2'
author: Issac Lee
date: '2019-10-04'
slug: stat2010-week7
categories:
  - R
tags:
  - stat2010
  - stat4200
header:
  caption: 'Image credit: [UIowaStat](https://stat.uiowa.edu/)'
  image: 'headers/stat2010_wide.png'
  preview: yes
---



<div id="sat.-and-act.-scores-standardization" class="section level2">
<h2>SAT. and ACT. Scores (Standardization)</h2>
<p>Let us assume you are working at the U of Iowa addmistration department. Every spring semester, you have many application from many future hawk eyes. Today, you have to pick one person to give an admission and you have these infomation about test score of three students;</p>
<p>Issac : SAT score - 1250 JAMES : SAT score - 1300 ROBERT: ACT score - 30</p>
<p>Which student should get the admission if the administration process are evaluated by only their test scores?</p>
<p>To pick the one student among these three, you want to see the distribution of the SAT and ACT scores for last year;</p>
<p><span class="math display">\[
SAT \sim \mathcal{N}(1200, 50) \\
ACT \sim \mathcal{N}(28, 2) \\
\]</span></p>
<p>Picking one between Issac and James is clear for us since James has higher score for the same test. How about between James and Robert? This is tricky, because these two students did not take the same test. Thus, we want to see how they did well in the exam comparing to other students scores.</p>
<pre class="r"><code>x &lt;- seq(1000, 1400, by = 10)
y &lt;- dnorm(x, mean = 1200, sd = 50)
plot(x, y, type = &quot;l&quot;,
     main = &quot;Distribution of SAT scores&quot;,
     xlab = &quot;SAT score&quot;,
     ylab = &quot;density&quot;)
abline(v = 1300)</code></pre>
<p><img src="/post/stat2010-week6_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<p>Q. Draw the density plot for ACT scores and mark the score or Robert.</p>
<p><details> <summary> Answer </summary></p>
<pre class="r"><code>x &lt;- seq(22, 34, by = 0.5)
y &lt;- dnorm(x, mean = 28, sd = 2)
plot(x, y, type = &quot;l&quot;,
     main = &quot;Distribution of ACT scores&quot;,
     xlab = &quot;ACT score&quot;,
     ylab = &quot;density&quot;)
abline(v = 30)</code></pre>
<p><img src="/post/stat2010-week6_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p></details></p>
<div id="standardization" class="section level3">
<h3>Standardization</h3>
<p>Using standardization of Normal distribution, we can obtain two numbers related to the two students scores whose scale is the same.</p>
<p><span class="math display">\[
\frac{data - \mu}{\sigma}
\]</span></p>
<p>Thus,</p>
<p><span class="math display">\[
\begin{align*}
Z_{James}  &amp; = \frac{1300 - 1200}{50} = 2 \\
Z_{Robert} &amp; = \frac{30 - 28}{2} = 1
\end{align*}
\]</span></p>
<pre class="r"><code># standadization
# (data - mean)/sd ~ N(0, 1)

# James
(1300 - 1200)/50 #2</code></pre>
<pre><code>## [1] 2</code></pre>
<pre class="r"><code># Robert
(30 - 28)/2      #1</code></pre>
<pre><code>## [1] 1</code></pre>
<p>James did relatively better than Robert based on the standadized score, thus, we need to give him an admission.</p>
<p>One thing that we should know about the standardization, the standardized value will follows the standard Normal distribution. Thus, using <code>R</code> functions we can calculate the quantiles for each score as follows;</p>
<pre class="r"><code>z_james &lt;- (1300 - 1200)/50
z_robert &lt;- (30 - 28)/2

# Put them in the standard Normal
x &lt;- seq(-3, 3, by = 0.1)
y &lt;- dnorm(x)
plot(x, y, type = &quot;l&quot;,
     main = &quot;Distribution of N(0, 1)&quot;,
     xlab = &quot;Standardized score&quot;,
     ylab = &quot;Density&quot;)

# James
abline(v = z_james, col = &quot;blue&quot;)

# Robert
abline(v = z_robert, col = &quot;red&quot;)</code></pre>
<p><img src="/post/stat2010-week6_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>Let us assume that the total number of students who took SAT or ACT last year was 10,000. Then, we can say there are about 1400 people between James and Robert for the following reason.</p>
<pre class="r"><code># percentile of scores for James and Robert
(pnorm(z_james) - pnorm(z_robert)) * 10000</code></pre>
<pre><code>## [1] 1359.051</code></pre>
<p>Let us consider the situation where the U of Iowa made a cut-off for application as follow;</p>
<pre><code>To apply the university, your score should be above the 90th percentile for whole group of students last year.</code></pre>
<p>This means, your score should be above 90th percentile. In the standard Normal,</p>
<pre class="r"><code>qnorm(0.9)</code></pre>
<pre><code>## [1] 1.281552</code></pre>
<p>1.281552 is the 90th percentile. Thus, if we mark the cut-off in the above plot, we can see that James can apply to the U of Iowa, but Robert is right below the threshold as follow;</p>
<pre class="r"><code>x &lt;- seq(-3, 3, by = 0.1)
y &lt;- dnorm(x)
plot(x, y, type = &quot;l&quot;,
     main = &quot;Distribution of N(0, 1)&quot;,
     xlab = &quot;Standardized score&quot;,
     ylab = &quot;Density&quot;)

# James
abline(v = z_james, col = &quot;blue&quot;)

# Robert
abline(v = z_robert, col = &quot;red&quot;)

# Add cut-off
abline(v = qnorm(0.9))</code></pre>
<p><img src="/post/stat2010-week6_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>We can find the cut off values for SAT and ACT using <code>qnorm</code> by setting the mean and sd for the each test.</p>
<pre class="r"><code># SAT cut-off
qnorm(0.9, mean = 1200, sd = 50)</code></pre>
<pre><code>## [1] 1264.078</code></pre>
<pre class="r"><code># ACT cut-off
qnorm(0.9, mean = 28, sd = 2)</code></pre>
<pre><code>## [1] 30.5631</code></pre>
<p>Thus, to apply to the U of Iowa, your SAT score should be above 1264.08 or your ACT score should be above 30.56.</p>
<p><a href="https://theissaclee.com/post/stat2010/" target="_self">Return to the course page</a></p>
</div>
</div>
